### ISSUE TITLE
Slow (200ms delay)

### ISSUE THREAD

**Issue by NKnusperer** [rebus-org/Rebus.Async#1]
Just tried this out because I thought it would be a nice solution to abstract a service from Rebus, e.g.  defining a interface with a signature like `Task<SomeReturnData> DoSomething(SomeInputData);`, then implement it using `IBus.SendRequest`. Pretty convenient.
However while with a classic reply handler and `IBus.Send` I could easily archive a few hundred request/replies per second `SendRequest` is very slow - maybe mostly because of the hard coded 200ms delay (https://github.com/rebus-org/Rebus.Async/blob/master/Rebus.Async/AsyncBusExtensions.cs#L76).

Are there any plans to make this more event-driven or is there a technical reason to do so?
Is there any other way to simulate a synchronously behavior?

**Comment by mookid8000** [comment]
I guess the hardcoded delay could easily be reduced to 10 ms or something like that... the important thing is that the thread gets to relax a bit while waiting, and even a few ms should be enough for that to happen.

You probably already thought of this, but please be aware that the request/reply thing is not really meant to replace a true synchronous request/response API like what you do over HTTP – it is only meant to be used in situations where e.g. you are using Rebus as a facade in front of an external web service or something like that.

I will release Rebus.Async 3 in a few seconds where I have decreased the reply-check interval to 10 ms 😄

**Comment by NKnusperer** [comment]
Thanks, but could you please explain a bit more what exactly you mean with  

> not really meant to replace a true synchronous request/response API like what you do over HTTP

Isn't HTTP request is normally a asynchronous operation?
E.g. in the old days before Tasks we used `HttpWebRequest` with the asynchronous programming model (`BeginGetResponse`, `EndGetResponse`) and now we have `HttpClient` were we can simlply do `await client.GetAsync` but obviosly it is still asynchronously (internally I think it is still APM).
Also is the underlying message transport system (e.g. RabbitMQ) not async anyway?

Maybe I get something wrong here so could you please outline a bit more when to use this extension and when not to.

**Comment by mookid8000** [comment]
> Isn't HTTP request is normally a asynchronous operation?
> E.g. in the old days before Tasks we used `HttpWebRequest` with the asynchronous programming model (`BeginGetResponse`, `EndGetResponse`) and now we have `HttpClient` were we can simlply do `await client.GetAsync` but obviosly it is still asynchronously (internally I think it is still APM).
> Also is the underlying message transport system (e.g. RabbitMQ) not async anyway?

Oh yeah, sure – it's asynchronous in the sense that a physical thread is not blocked while waiting for the response.

But conceptually it is synchronous because every request yields a response, and we wait somehow for that response.

My point is that there are SO many nice things in the HTTP protocol that you are missing out on if you use Rebus' crude request/response API from `Rebus.Async` throughout. So I am basically saying that you should probably only use `Rebus.Async` in a few places, because if you feel like you need it in more places, I would suggest that you look at using HTTP instead.

Just my two cents 😄
