### ISSUE TITLE
Use SendRequest with Bus.Advanced.Routing?

### ISSUE THREAD

**Issue by pwelzien** [rebus-org/Rebus.Async#22]
Would it be possible to extend the SendRequest method in Bus.Advanced.Routing or do you see any problems with the current design or other limitations?

What I'm currently looking for is to be able to provide a specific queue name which is only available in the Bus.Advanced.Routing.Send method.

Best regards,

Peter

**Comment by mookid8000** [comment]
Turned out it was pretty easy to add 🙂 

If you update to Rebus.Async 9.0.0 you'll find a new `SendRequest` extension method on `IRoutingApi`, so you can do this:


```csharp
var routing = bus.Advanced.Routing;
var reply = await routing.SendRequest<SomeReply>("recipient", new SomeRequest());
```
