### ISSUE TITLE
Does this library work in multi-instance scenario?

### ISSUE THREAD

**Issue by macchmie3** [rebus-org/Rebus.Async#25]
Hi,

I have a scenario when I use sql-server transport in lease mode.
I have 2 apps (both are multiple instances).

Producer app sends message with  "SendRequest<TReply>" to the Reciver app. Reciver app correctly places the TReply in Producer's input queue. The problem is that Producer app has 2 instances, and sometimes the instance that did not produce the request recives the reply.
In such case I see following log by that instance:
"Received message with message ID "request-reply_4046c675-d984-4715-a0c9-d0e27ec56c18", which was determined to be a reply to be handled as an inline request-reply reply (because of the "request-reply" prefix), BUT the dictionary of task completion sources did NOT contain an entry for that ID"

Then the message is imidiately transffered to poison queue and the instance that was indeed waiting for this reply has no chance to handle it.

**Comment by mookid8000** [comment]
Rebus.Async DOESN'T WORK when there's multiple instances consuming replies from the same input queue!

It just doesn't.

There's actually no way it could.

One of the web application instances would sit there waiting for a reply, but the other instance would receive it. How would it know? It can't.

Here's a quote from [the README](https://github.com/rebus-org/Rebus.Async/blob/master/README.md):

> The reason is that the requestor holds transient state after having issued a request, which will be lost if the process crashes, which in turn will result in a reply that has noone to handle it.
>
> This might not be a problem, but I generally recommend that you try to model your code such that your messaging is truly asynchronous (i.e. requestors send their requests, replies are handled in a separate handler, possibly correlated with whatever you were doing by means of a correlation ID).

and in this case "multiple instances" would achieve the same result as a process that had crashed: It would just not have any recollection of which requests it had sent, and it would now know what code to potentially execute when receiving a reply message.

I hope it makes sense 🙂 let me know if I should explain this further or differently somehow

**Comment by macchmie3** [comment]
It's quite clear. I just wanted to make sure. I was thinking that could be somehow be achievable since:

- an instance that does "SendRequest" specifies a timeout so in general a reply could have "time-to-live" property
- an instance will grab a reply and return it back to the queue if it is not in "dictionary of task completion sources", UNLESS that reply is past it's "time-to-live", then it should be considered lost, crashed, unhandled.

I understand that queue's in general work in the manner of "grab and handle 1st available message" so a mechanism from 2nd point would porbably be a huge anti-pattern.

@mookid8000
