### ISSUE TITLE
Replace Task.Delay to TaskCompletionSorce

### ISSUE THREAD

**Issue by MaratFattakhov** [rebus-org/Rebus.Async#7]
Hi mookid8000!

I am very pleased to use Rebus and Rebus.Async. I had got a question when reviewed the library.
What do you think about replacing while loop with Task.Delay(10) to using TaskCompletionSource ?
To store in ConcurrentDictionary TaskCompletionSources instead of TimedMessage.

Perhaps it has any reason why it was made that?

**Comment by mookid8000** [comment]
It's made that way because I didn't know better at the time 😀 if you're interested in improving the library, I would be very happy to accept your PR!

**Comment by matt-psaltis** [comment]
I have these changes with passing tests in a local commit however it requires net46 due to TaskContinuationOptions.RunContinuationsAsynchronously to avoid continuations running on the reply message thread. Is this of use given the framework limitation?

**Comment by mookid8000** [comment]
Yes, definitely! Feel free to adjust the targets accordingly. 😄

**Comment by mookid8000** [comment]
You did it 👍 

Btw. I just released Rebus.Async 6.0.2, which completely removes the need for background cleaning of task completion sources, as they're removed either when a reply is received, or when the request times out.

**Comment by matt-psaltis** [comment]
Nice one! That is a very good idea and I'm kicking myself I didn't do it :)

**Comment by mookid8000** [comment]
😁 please don't kick yourself
